# Generated by Django 4.1.7 on 2023-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_linkk'),
    ]

    operations = [
        migrations.CreateModel(
            name='heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAG', models.CharField(max_length=10)),
                ('TEXT', models.CharField(max_length=255)),
            ],
        ),
    ]
