# Generated by Django 4.1.7 on 2023-03-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='Links',
        ),
        migrations.RemoveField(
            model_name='links',
            name='text',
        ),
    ]
